name: Padavan Builder

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DEVICE: K2P
      BLOCK_SIZE: 15872
      ZT_MODE: "y"

    steps:
    # ========== 代码检出 ==========
    - name: Checkout code
      uses: actions/checkout@v4

    # ========== 依赖安装 ==========
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          unzip libtool-bin curl cmake gperf gawk flex bison \
          fakeroot kmod cpio git python3-docutils gettext

    # ========== 源码准备 ==========
    - name: Clone source
      run: |
        git clone --depth=1 https://github.com/hanwckf/padavan-4.4.git
        cd padavan-4.4/toolchain-mipsel
        ./dl_toolchain.sh
        mkdir -p /opt/images

    # ========== 配置阶段 ========== (关键修复区域)
    - name: Configure firmware
      run: |  # 第60行
        cd padavan-4.4/trunk
        
        # 验证模板存在
        [ ! -f "configs/templates/${DEVICE}.config" ] && {
          echo "::error::Missing template for ${DEVICE}"
          exit 1
        }

        # 应用基础配置
        cp "configs/templates/${DEVICE}.config" .config

        # ========== 第61行关键修复 ==========
        # 清理旧配置项（精确匹配）
        sed -i '/^CONFIG_FIRMWARE_INCLUDE_ZEROTIER=/d' .config
        sed -i '/^CONFIG_FIRMWARE_INCLUDE_ADBYBY=/d' .config

        # 写入新配置（修复heredoc语法）
        cat << 'EOF' >> .config  # 必须保持顶格
CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y
CONFIG_FIRMWARE_INCLUDE_ZEROTIER=${ZT_MODE}
CONFIG_FIRMWARE_INCLUDE_ADBYBY=n
EOF

    # ========== 构建阶段 ==========
    - name: Build firmware
      run: |
        cd padavan-4.4/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify "${DEVICE}" "${BLOCK_SIZE}"
        sudo mv images/*.trx /opt/images/

    # ========== 产物上传 ==========
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${DEVICE}-Firmware
        path: /opt/images/*.trx
