name: Padavan Firmware Builder

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DEVICE: K2P
      REPO_URL: https://github.com/MeIsReallyBa/padavan-4.4.git

    steps:
    - name: Clone repository
      run: |
        # 方案一：如果 trunk 是分支
        # git clone -b trunk ${{ env.REPO_URL }} padavan
        
        # 方案二：如果 trunk 是目录
        git clone --depth=1 ${{ env.REPO_URL }} padavan
        cd padavan
        
        echo "=== 仓库结构验证 ==="
        git branch -a
        echo "1. 检查分支：" && git rev-parse --abbrev-ref HEAD
        echo "2. 检查 trunk 目录：" && ls -ld trunk
        echo "3. 检查模板文件：" && find . -name "$DEVICE.config"

    - name: Build Setup
      run: |
        cd padavan
        
        # 动态路径处理
        if [ -d "trunk" ]; then
          WORK_DIR="trunk"
        else
          WORK_DIR="."
        fi
        
        echo "WORK_DIR=$WORK_DIR" >> $GITHUB_ENV
        echo "最终工作路径：$WORK_DIR"
        ls -l $WORK_DIR/configs/templates/
