name: Padavan AutoBuilder

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DEVICE: K2P
      BLOCK_SIZE: 15872
      ZT_ENABLED: "y"

    steps:
    # ========== 代码检出 ==========
    - name: Checkout code
      uses: actions/checkout@v4

    # ========== 依赖安装 ==========
    - name: Install dependencies
      run: |  # 缩进0级
        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          unzip libtool-bin curl cmake gperf gawk flex bison \
          fakeroot kmod cpio git python3-docutils gettext automake autopoint \
          texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin \
          libssl-dev libjson-c-dev

    # ========== 源码准备 ==========
    - name: Prepare source
      run: |  # 缩进0级
        git clone --depth=1 https://github.com/hanwckf/padavan-4.4.git || { echo "::error::Clone failed"; exit 1; }
        cd padavan-4.4/toolchain-mipsel || { echo "::error::Directory missing"; exit 1; }
        ./dl_toolchain.sh
        sudo mkdir -p /opt/images

    # ========== 配置阶段 ========== (关键修复区)
    - name: Configure firmware
      shell: bash
      run: |  # 缩进0级（第54行所在位置）
          # ↓ 以下内容统一缩进2个空格
          cd padavan-4.4/trunk || { echo "::error::Can't enter trunk"; exit 1; }

          # 模板验证
          if [[ ! -f "configs/templates/${DEVICE}.config" ]]; then
            echo "::error::[${DEVICE}] Template not found"
            exit 1
          fi

          # 应用配置
          cp -vf "configs/templates/${DEVICE}.config" .config

          # 清理配置项
          declare -a CONFIG_CLEAN=(
            "CONFIG_FIRMWARE_INCLUDE_ZEROTIER"
            "CONFIG_FIRMWARE_INCLUDE_ADBYBY"
          )
          for target in "${CONFIG_CLEAN[@]}"; do
            sed -i "/^${target}=/d" .config
          done

          # 写入配置（零缩进内容）
          cat << 'EOF' >> .config
CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y
CONFIG_FIRMWARE_INCLUDE_ZEROTIER=${ZT_ENABLED}
CONFIG_FIRMWARE_INCLUDE_ADBYBY=n
EOF

    # ========== 构建阶段 ==========
    - name: Build firmware
      run: |  # 缩进0级
          cd padavan-4.4/trunk || { echo "::error::Trunk missing"; exit 1; }
         
