name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        # 修复镜像源
        sudo sed -i 's/azure.archive.ubuntu.com/archive.ubuntu.com/g' /etc/apt/sources.list
        sudo sed -i 's/security.ubuntu.com/security.ubuntu.com/g' /etc/apt/sources.list
        
        # 安装依赖（新增 ZeroTier 所需依赖）
        sudo apt update -y
        sudo apt install -y --fix-missing \
          unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
          fakeroot kmod cpio git python3-docutils gettext automake autopoint \
          texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin \
          libssl-dev libnatpmp-dev

    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/padavan-4.4.git
        cd padavan-4.4/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: Build Firmware
      env:
        TNAME: K2P  # 修改为实际型号
        BLOCK_SIZE: 15872  # K2P专用块大小
      run: |
        cd padavan-4.4/trunk
        if [ ! -f configs/templates/$TNAME.config ]; then
          echo "::error::模板文件 configs/templates/$TNAME.config 不存在"
          exit 1
        fi
        
        # 基础配置
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config

        # 清理旧配置（新增 ZeroTier 相关项）
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config  # 新增清理项

        # 写入新配置（启用 ZeroTier）
        cat >> .config <<EOF
CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y
CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n
CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n
CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n
CONFIG_FIRMWARE_INCLUDE_SSOBFS=n
CONFIG_FIRMWARE_INCLUDE_ADBYBY=n
CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n
CONFIG_FIRMWARE_INCLUDE_SRELAY=n
CONFIG_FIRMWARE_INCLUDE_XRAY=n
CONFIG_FIRMWARE_INCLUDE_V2RAY=n
CONFIG_FIRMWARE_INCLUDE_DDNSTO=n
CONFIG_FIRMWARE_INCLUDE_ALDRIVER=n
CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n
CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n
CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n
CONFIG_FIRMWARE_INCLUDE_TROJAN=n
CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n
CONFIG_FIRMWARE_INCLUDE_CADDY=n
CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n
CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n
CONFIG_FIRMWARE_INCLUDE_WYY=n
CONFIG_FIRMWARE_INCLUDE_WYYBIN=n
CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n
EOF

        # 空间优化构建
        sudo ./clear_tree
        if ! sudo ./build_firmware_modify $TNAME $BLOCK_SIZE; then
          echo "::warning::构建失败，尝试缩减 1MB 空间重试..."
          sudo ./build_firmware_modify $TNAME $(($BLOCK_SIZE - 1024))
        fi

        # 产物处理
        if ls images/*.trx >/dev/null 2>&1; then
          sudo mv -f images/*.trx /opt/images/
        else
          echo "::error::未找到固件文件！"
          exit 1
        fi

    - name: Upload packages
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Padavan-${{ env.TNAME }}-$(date +%Y%m%d)
        path: /opt/images/*.trx
