name: Padavan Firmware Builder

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    env:
      DEVICE: K2P  # 需与模板文件名一致
      REPO_URL: https://github.com/MeIsReallyBa/padavan-4.4.git

    steps:
    # ==================== 1. 环境准备 ====================
    - name: Setup environment
      run: |
        # 设置国内镜像源
        sudo sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
        sudo sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
        
        # 安装基础依赖
        sudo apt update -y
        sudo apt install -y --no-install-recommends \
          unzip libtool-bin curl cmake gperf gawk flex bison \
          fakeroot kmod cpio git python3-docutils gettext \
          texinfo build-essential help2man pkg-config \
          zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev \
          libncurses5-dev libltdl-dev xxd squashfs-tools

    # ==================== 2. 获取源码 ====================
    - name: Clone repository
      run: |
        # 修复点：明确指定 trunk 分支
        git clone --depth=1 -b trunk ${{ env.REPO_URL }} padavan
        cd padavan
        
        # 验证仓库结构（移除 trunk/ 前缀）
        echo "=== 仓库分支信息 ==="
        git branch -a
        echo "=== 关键目录检查 ==="
        ls -l toolchain-mipsel configs/templates/

    # ==================== 3. 工具链配置 ====================
    - name: Setup toolchain
      run: |
        cd padavan/toolchain-mipsel
        
        # 清理旧文件
        rm -rf toolchain-mipsel mipsel-linux-uclibc*
        
        # 下载工具链（带重试机制）
        for i in {1..3}; do
          ./dl_toolchain.sh && break || sleep 30
        done
        
        # 解压验证
        if [ ! -f "mipsel-linux-uclibc.tar.xz" ]; then
          echo "::error::工具链下载失败"
          exit 1
        fi
        tar -xvf mipsel-linux-uclibc.tar.xz
        
        # 路径自动检测
        if [ -d "toolchain-mipsel" ]; then
          echo "TOOLCHAIN_DIR=toolchain-mipsel" >> $GITHUB_ENV
        else
          echo "TOOLCHAIN_DIR=mipsel-linux-uclibc" >> $GITHUB_ENV
        fi
        
        # 权限修复
        chmod -R +x ${{ env.TOOLCHAIN_DIR }}
        
        # 编译器验证
        echo "=== 工具链信息 ==="
        ${{ env.TOOLCHAIN_DIR }}/bin/mipsel-linux-uclibc-gcc --version || {
          echo "::error::工具链验证失败";
          exit 1;
        }

    # ==================== 4. 编译配置 ====================
    - name: Configure build
      run: |
        cd padavan
        
        # 修复点：移除 trunk/ 路径层级
        CONFIG_FILE="configs/templates/${{ env.DEVICE }}.config"
        if [ ! -f "$CONFIG_FILE" ]; then
          echo "::error::设备配置文件 $CONFIG_FILE 不存在"
          ls configs/templates/
          exit 1
        fi
        
        # 初始化配置
        cp -v "$CONFIG_FILE" .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_IPV6_NAT=y" >> .config

    # ==================== 5. 执行编译 ====================
    - name: Build firmware
      run: |
        cd padavan
        
        # 设置工具链路径
        echo "PATH=$PATH:$PWD/toolchain-mipsel/${{ env.TOOLCHAIN_DIR }}/bin" >> $GITHUB_ENV
        
        # 清理并编译
        ./clear_tree
        echo "=== 开始编译 ==="
        fakeroot ./build_firmware_modify ${{ env.DEVICE }} -j$(nproc)
        
        # 输出目录验证
        if [ ! -d "images" ]; then
          echo "::error::编译失败，未生成镜像目录"
          exit 1
        fi

    # ==================== 6. 产物验证 ====================
    - name: Verify firmware
      run: |
        TRX_FILE=$(ls padavan/images/*.trx | head -n1)
        
        # 基础检查
        if [ $(stat -c%s "$TRX_FILE") -lt 8000000 ]; then
          echo "::error::固件大小异常: $(du -h $TRX_FILE)"
          exit 1
        fi
        
        # 文件结构验证
        echo "=== Binwalk分析 ==="
        binwalk $TRX_FILE | grep 'Squashfs filesystem' || {
          echo "::error::文件系统验证失败";
          exit 1;
        }

    # ==================== 7. 发布产物 ====================
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.DEVICE }}-firmware
        path: padavan/images/*.trx
        retention-days: 7

    # ==================== 8. 环境清理 ====================
    - name: Cleanup
      if: always()
      run: |
        sudo rm -rf padavan
