name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt install -y \
          unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
          fakeroot kmod cpio git python3-docutils gettext automake autopoint \
          texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin

    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/padavan-4.4.git
        cd padavan-4.4/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: Build Firmware
      env:
        TNAME: K2P  # 确保与模板名称一致
        BLOCK_SIZE: 15872
      run: |  # 这是第70行，修复缩进问题
        cd padavan-4.4/trunk
        # 验证模板文件存在
        if [ ! -f "configs/templates/$TNAME.config" ]; then
          echo "::error::模板文件 configs/templates/$TNAME.config 不存在"
          exit 1
        fi
        
        # 应用基础配置
        cp -f "configs/templates/$TNAME.config" .config
        
        # 清理旧配置项
        declare -a CONFIG_CLEAN=(
          "CONFIG_FIRMWARE_INCLUDE_MENTOHUST"
          "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT"
          "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS"
          "CONFIG_FIRMWARE_INCLUDE_SSSERVER"
          "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER"
          "CONFIG_FIRMWARE_INCLUDE_ADBYBY"
          "CONFIG_FIRMWARE_INCLUDE_FRPC"
          "CONFIG_FIRMWARE_INCLUDE_FRPS"
          "CONFIG_FIRMWARE_INCLUDE_TUNSAFE"
          "CONFIG_FIRMWARE_INCLUDE_ALIDDNS"
          "CONFIG_FIRMWARE_INCLUDE_SMARTDNS"
          "CONFIG_FIRMWARE_INCLUDE_SRELAY"
          "CONFIG_FIRMWARE_INCLUDE_ZEROTIER"  # 新增清理项
        )
        for item in "${CONFIG_CLEAN[@]}"; do
          sed -i "/$item/d" .config
        done

        # 写入新配置（修复EOF缩进）
        cat << 'EOF' >> .config
CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y
CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y
CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n
CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n
CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n
CONFIG_FIRMWARE_INCLUDE_SSOBFS=n
CONFIG_FIRMWARE_INCLUDE_ADBYBY=n
CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n
CONFIG_FIRMWARE_INCLUDE_SRELAY=n
CONFIG_FIRMWARE_INCLUDE_XRAY=n
CONFIG_FIRMWARE_INCLUDE_V2RAY=n
CONFIG_FIRMWARE_INCLUDE_DDNSTO=n
CONFIG_FIRMWARE_INCLUDE_ALDRIVER=n
CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n
CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n
CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n
CONFIG_FIRMWARE_INCLUDE_TROJAN=n
CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n
CONFIG_FIRMWARE_INCLUDE_CADDY=n
CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n
CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n
CONFIG_FIRMWARE_INCLUDE_WYY=n
CONFIG_FIRMWARE_INCLUDE_WYYBIN=n
CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n
EOF

        # 构建命令（修复缩进）
        sudo ./clear_tree
        if ! sudo ./build_firmware_modify "$TNAME" "$BLOCK_SIZE"; then
          echo "::warning::构建失败，尝试缩减空间重试..."
          sudo ./build_firmware_modify "$TNAME" $((BLOCK_SIZE - 1024))
        fi
        
        # 移动产物（修复路径处理）
        if ls images/*.trx >/dev/null 2>&1; then
          sudo mv -v images/*.trx /opt/images/
        else
          echo "::error::未找到固件文件"
          exit 1
        fi

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: Padavan-${{ env.TNAME }}
        path: /opt/images/*.trx
