name: Build Padavan

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DEVICE_MODEL: K2P
      BLOCK_SIZE: 15872  # 单位KB
      ZT_ENABLED: "y"    # ZeroTier开关

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y \
          unzip libtool-bin curl cmake gperf gawk flex bison \
          fakeroot kmod cpio git python3-docutils gettext

    - name: Clone source
      run: |
        git clone --depth=1 https://github.com/hanwckf/padavan-4.4.git
        cd padavan-4.4/toolchain-mipsel
        ./dl_toolchain.sh

    # ========== 关键修复区域 (原第91行附近) ==========
    - name: Configure build
      run: |  # 第91行的正确缩进开始
        cd padavan-4.4/trunk
        
        # 验证模板文件存在
        [ ! -f "configs/templates/${DEVICE_MODEL}.config" ] && {
          echo "::error::Missing template for ${DEVICE_MODEL}"
          exit 1
        }

        # 应用基础配置
        cp "configs/templates/${DEVICE_MODEL}.config" .config

        # 清理旧配置（精确匹配）
        sed -i '/^CONFIG_FIRMWARE_INCLUDE_ZEROTIER=/d' .config
        sed -i '/^CONFIG_FIRMWARE_INCLUDE_ADBYBY=/d' .config

        # 写入新配置（修复heredoc语法）
        cat << 'EOF' >> .config  # 第91行实际位置
CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y
CONFIG_FIRMWARE_INCLUDE_ZEROTIER=${ZT_ENABLED}
CONFIG_FIRMWARE_INCLUDE_ADBYBY=n
EOF

    - name: Build firmware
      run: |
        cd padavan-4.4/trunk
        sudo ./clear_tree
        
        # 带空间限制的构建命令
        if ! sudo ./build_firmware_modify "${DEVICE_MODEL}" "${BLOCK_SIZE}"; then
          echo "::warning::Retrying with reduced size..."
          sudo ./build_firmware_modify "${DEVICE_MODEL}" $((BLOCK_SIZE - 1024))
        fi
        
        # 移动产物
        sudo mv -v images/*.trx /opt/images/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${DEVICE_MODEL}-$(date +%s)
        path: /opt/images/*.trx
