name: Build Padavan

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DEVICE: K2P        # 设备型号
      BLOCK_SIZE: 15872  # 块大小(KB)

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          unzip libtool-bin curl cmake \
          gperf gawk flex bison \
          fakeroot kmod cpio \
          git python3-docutils gettext \
          texinfo build-essential \
          zlib1g-dev libgmp3-dev

    - name: Clone source code
      run: |
        git clone --depth=1 \
          https://github.com/MeIsReallyBa/padavan-4.4.git
        cd padavan-4.4/toolchain-mipsel
        ./dl_toolchain.sh

    - name: Configure build
      run: |
        cd padavan-4.4/trunk
        [ ! -f "configs/templates/${DEVICE}.config" ] && exit 1
        cp "configs/templates/${DEVICE}.config" .config
        
        # 清理并更新配置
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config

    - name: Build firmware
      run: |
        cd padavan-4.4/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify "$DEVICE" "$BLOCK_SIZE"
        
        # 关键修复：创建目标目录后再移动文件
        sudo mkdir -p /opt/images  # 确保目录存在
        sudo mv images/*.trx /opt/images/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DEVICE }}-Firmware
        path: /opt/images/*.trx
